#!/bin/bash
set -Eeux

# Check if the correct number of arguments is provided
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <depthai-git-version>"
    exit 1
fi

DEPTHAI_GIT_VERSION=$1
echo "Received DepthAI Git version: $DEPTHAI_GIT_VERSION"

# Verify that the version starts with 'git+'
if [[ $DEPTHAI_GIT_VERSION != git+* ]]; then
    echo "Error: DepthAI version must be a Git URL"
    exit 1
fi

# Install necessary build tools and dependencies for compiling the DepthAI Python package from source
apt-get update -qq && \
apt-get install -qq --no-install-recommends \
python3 python3-dev python3-pip \
ca-certificates \
git \
wget \
cmake \
make \
build-essential && \
pip3 install mypy && \
rm -rf /var/lib/apt/lists/*

# Parse the Git URL and Branch from the version string
GIT_URL=${DEPTHAI_GIT_VERSION/git+/}
BRANCH=${GIT_URL##*@}
GIT_URL=${GIT_URL%@*}
echo "Cloning from Git URL: $GIT_URL, Branch: $BRANCH"


# Clone the DepthAI Git repository
echo "Cloning DepthAI from Git..."
git clone --branch "$BRANCH" --recurse-submodules "$GIT_URL" depthai-python || { echo "Git clone failed"; exit 1; }

# Navigate to the cloned directory
echo "Navigating to cloned directory..."
cd depthai-python || { echo "Failed to enter depthai-python directory"; exit 1; }

# Build and install the package
echo "Building and installing the DepthAI package..."
pip3 install . --verbose || { echo "DepthAI installation failed"; exit 1; }

echo "DepthAI installation from Git completed successfully."
