#!/bin/bash

# Check for correct number of arguments
if [[ $# -ne 3 ]]; then
    echo "Usage: $0 <robotics-vision-core> <robothub-version> <depthai-sdk-version>"
    echo "robotics-vision-core: rvc2, rvc3, rvc2-depthaiV3"
    exit 1
fi

ROBOTICS_VISION_CORE=$1
ROBOTHUB_VERSION=$2
DEPTHAI_SDK_VERSION=$3

# Install robothub
pip3 install --no-deps --no-cache-dir "robothub==${ROBOTHUB_VERSION}"

# Install depthai-sdk based on the robotics-vision-core
if [[ "$ROBOTICS_VISION_CORE" == "rvc2" || "$ROBOTICS_VISION_CORE" == "rvc2-depthaiV3" ]]; then
    pip3 install --no-deps --no-cache-dir "depthai-sdk==${DEPTHAI_SDK_VERSION}"
elif [[ "$ROBOTICS_VISION_CORE" == "rvc3" ]]; then
    pip3 install --no-deps --no-cache-dir "git+https://github.com/luxonis/depthai.git@${DEPTHAI_SDK_VERSION}#subdirectory=depthai_sdk"
else
    echo "Unknown ROBOTICS_VISION_CORE: ${ROBOTICS_VISION_CORE}"
    exit 1
fi
