ARG FROM_IMAGE_TAG
FROM ${FROM_IMAGE_TAG}

RUN set -eux & apk add --no-cache curl nodejs npm alpine-sdk bash libstdc++ libc6-compat

RUN npm config set python python3
RUN npm install -g yarn

RUN yarn global add code-server@4.5.1
ADD docker/vscode.config /vscode.config

ADD docker/launch-vscode.sh /usr/local/bin/launch-vscode.sh
RUN chmod +x /usr/local/bin/launch-vscode.sh

RUN mkdir -p /data/vscode/extensions

RUN code-server --extensions-dir /data/vscode/extensions --install-extension redhat.vscode-yaml
RUN code-server --extensions-dir /data/vscode/extensions --install-extension ms-python.python
RUN code-server --extensions-dir /data/vscode/extensions --install-extension vscode.docker

VOLUME /app

ENV CODE_SERVER_BIND_ADDR=0.0.0.0:9999

CMD ["launch-vscode.sh"]