ARG FROM_IMAGE_TAG
FROM ${FROM_IMAGE_TAG}

RUN set -eux & apt-get update && apt-get install curl build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev python-is-python3

ARG NODE_VERSION=16.16.0
# node install
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

RUN npm config set python python3
RUN npm install -g yarn

RUN wget https://github.com/cloudflare/cloudflared/releases/download/2022.7.1/cloudflared-linux-${TARGETARCH}.deb -P /root \
  && dpkg -i /root/cloudflared-linux-${TARGETARCH}.deb

RUN yarn global add code-server@4.5.1
ADD docker/vscode.config /vscode.config

ADD docker/launch-vscode.sh /usr/local/bin/launch-vscode.sh
RUN chmod +x /usr/local/bin/launch-vscode.sh

RUN mkdir -p /data/vscode/extensions

RUN code-server --extensions-dir /data/vscode/extensions --install-extension redhat.vscode-yaml
RUN code-server --extensions-dir /data/vscode/extensions --install-extension ms-python.python
RUN code-server --extensions-dir /data/vscode/extensions --install-extension vscode.docker

VOLUME /app

ENV CODE_SERVER_BIND_ADDR=0.0.0.0:9999

CMD ["launch-vscode.sh"]