ARG FROM_IMAGE_TAG
FROM ${FROM_IMAGE_TAG}

RUN set -eux & apt-get update && apt-get install nodejs npm bash build-essential
RUN npm config set python python3
RUN npm install -g node-addon-api

RUN npm install -g code-server
ADD docker/vscode.config /vscode.config
RUN mkdir -p /data/vscode/extensions

RUN code-server --extensions-dir /data/vscode/extensions --install-extension redhat.vscode-yaml
RUN code-server --extensions-dir /data/vscode/extensions --install-extension ms-python.python
RUN code-server --extensions-dir /data/vscode/extensions --install-extension vscode.docker

VOLUME /app

ENV CODE_SERVER_BIND_ADDR=0.0.0.0:9999

CMD ["code-server", "--config", "/vscode.config", "--bind-addr", "\"${CODE_SERVER_BIND_ADDR}\"", "/app"]