name: Build podman for ubuntu
concurrency: aws-worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish-podman.yml'
      - 'containers/podman-ubuntu/**/*'

env:
  GO_LANG_VERSION: '1.17'
  CONMON_VERSION: '2.1.5'
  CNI_PLUGINS_VERSION: '1.1.1'
  CRUN_VERSION: '1.7'
  PODMAN_VERSION: '4.3.1'
  NETAVARK_VERSION: '1.3.0'
  AARDVARK_DNS_VERSION: '1.3.0'

  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_X86_IMAGE_ID: ${{ secrets.AWS_X86_IMAGE_ID }}
  AWS_ARM64_IMAGE_ID: ${{ secrets.AWS_ARM64_IMAGE_ID }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:
    name: Build Agent
    strategy:
      matrix:
        os: [buildjet-8vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204-arm]
        include:
          - os: buildjet-8vcpu-ubuntu-2204
            arch: x86_64
          - os: buildjet-8vcpu-ubuntu-2204-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '^${{ env.GO_LANG_VERSION }}'
      - 
        name: Setup common apt deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc git make gettext-base runc libsystemd-dev libseccomp-dev libc6-dev libglib2.0-dev
      -
        name: Build conmon
        working-directory: ./containers/podman-ubuntu
        run: |
          mkdir -p ./packages/conmon
          sh ./conmon/build.sh
      -
        name: Build netavark
        working-directory: ./containers/podman-ubuntu
        run: |
          sh ./netavark/build.sh
      -
        name: Download crun
        working-directory: ./containers/podman-ubuntu
        run: |
          mkdir -p ./packages/crun
          wget -O "$(pwd)/packages/crun/crun_${CRUN_VERSION}_x86_64" https://github.com/containers/crun/releases/download/${CRUN_VERSION}/crun-${CRUN_VERSION}-linux-amd64
          wget -O "$(pwd)/packages/crun/crun_${CRUN_VERSION}_aarch64" https://github.com/containers/crun/releases/download/${CRUN_VERSION}/crun-${CRUN_VERSION}-linux-arm64
      -
        name: Build podman
        working-directory: ./containers/podman-ubuntu
        run: |
          sudo apt-get install btrfs-progs iptables libassuan-dev libbtrfs-dev libdevmapper-dev libgpgme-dev libgpg-error-dev libprotobuf-dev libprotobuf-c-dev libselinux1-dev uidmap libapparmor-dev 
          sh ./podman/build.sh
      -
        name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: containers/podman-ubuntu/packages
