name: Build podman for ubuntu
concurrency: aws-worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish-podman.yml'
      - 'containers/podman-ubuntu/**/*'

env:
  GO_LANG_VERSION: '1.17.13'
  CONMON_VERSION: '2.1.5'
  CNI_PLUGINS_VERSION: '1.1.1'
  CRUN_VERSION: '1.7'
  PODMAN_VERSION: '4.4.1'
  NETAVARK_VERSION: '1.3.0'
  AARDVARK_DNS_VERSION: '1.3.0'

  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_X86_IMAGE_ID: ${{ secrets.AWS_X86_IMAGE_ID }}
  AWS_ARM64_IMAGE_ID: ${{ secrets.AWS_ARM64_IMAGE_ID }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:
    name: Build Agent
    strategy:
      matrix:
        os: [buildjet-8vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204-arm]
        include:
          - os: buildjet-8vcpu-ubuntu-2204
            arch: x86_64
          - os: buildjet-8vcpu-ubuntu-2204-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Prepare builder
        working-directory: ./containers/podman-ubuntu
        run: |
          docker build -t podman-builder --build-arg "GO_LANG_VERSION=${GO_LANG_VERSION}" .
      -
        name: Build
        working-directory: ./containers/podman-ubuntu
        run: |
          mkdir -p ./packages/crun
          wget -O "$(pwd)/packages/crun/crun_${CRUN_VERSION}_x86_64" https://github.com/containers/crun/releases/download/${CRUN_VERSION}/crun-${CRUN_VERSION}-linux-amd64
          wget -O "$(pwd)/packages/crun/crun_${CRUN_VERSION}_aarch64" https://github.com/containers/crun/releases/download/${CRUN_VERSION}/crun-${CRUN_VERSION}-linux-arm64
          docker run -e CONMON_VERSION -e ARCH -e PKG_ROOT -e NETAVARK_VERSION -e AARDVARK_DNS_VERSION -e PODMAN_VERSION -v `pwd`:/app podman-builder
      -
        name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: containers/podman-ubuntu/packages
