name: Build and publish patched libusb

on:
  workflow_dispatch:

jobs:
  build-libusb:
    name: Build & publish patched libusb
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runner:
          - {runs-on: buildjet-2vcpu-ubuntu-2204, arch: x86_64}
          - {runs-on: buildjet-2vcpu-ubuntu-2204-arm, arch: aarch64}
    runs-on: ${{ matrix.runner.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq --no-install-recommends ca-certificates wget bzip2 build-essential
      - name: Build libusb
        working-directory: external/libusb/
        run: |
          wget https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26.tar.bz2
          tar xf libusb-1.0.26.tar.bz2
          cp linux_netlink.c libusb-1.0.26/libusb/os/linux_netlink.c
          cd libusb-1.0.26
          ./configure --disable-udev
          make -j$(nproc)
      - name: Upload to bucket
        working-directory: external/libusb/
        env:
          ARCHITECTURE: ${{ matrix.runner.arch }}
          AWS_ACCESS_KEY_ID: ${{ secrets.RH_PUBLIC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RH_PUBLIC_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.RH_PUBLIC_ENDPOINT }}
        run: aws s3 cp libusb-1.0.26/libusb/.libs/libusb-1.0.so.0.3.0 s3://rh-public/libusb/1.0.26/libusb-$ARCHITECTURE.so
